### ISSUE TITLE
Typos and corrections in the paper

### ISSUE THREAD

**Issue by divijghose** [umami-hep/salt#1]
Hello, 

After reviewing the paper for JOSS, I have found the following typos:
1. Line 19: "configurabiltiy" should be "configurability"
2. Line 50: "admist" should be "amidst"
3. Line 63: "concatentated" should be "concatenated"

Could you please look into this, thanks!

**Comment by samvanstroud** [comment]
Hi @divijghose, many thanks for the review! The typos have been fixed in https://github.com/umami-hep/salt/commit/3a5093965d14ab653bf34280b860daa43addb205
